author: Jadedwolf
database: false
description: "Prevents players from building mob farms by only allowing items to drop\
  \ from those killed by players themselves.\r\nAll Credits go to: McSpazzy"
main: jadedwolf.plugins.nofarm.NoFarm
name: NoFarm
startup: postworld
url: http://jadedwolf.com/
version: '0.7'
authors:
  - McSpazzy
    - Jadedwolf
